[build]
publish = "static"
command = "pnpm build & pnpm ssg"

[[redirects]]
from = "/api/*"
to = "/api/:splat.json"
status = 200

[[redirects]]
from = "/static/*"
to = "/:splat"
status = 200

[[redirects]]
from = "/favicon.ico"
to = "/icon/favicon.ico"
status = 200
