[build]
publish = "static"
command = "bun run build & bun run ssg"
edge_functions = "api"

[functions]
deno_import_map = "./api/importmap.json"

[[redirects]]
from = "/api/*"
to = "/api/:splat.json"
status = 200

[[redirects]]
from = "/static/*"
to = "/:splat"
status = 200

[[redirects]]
from = "/favicon.ico"
to = "/icon/favicon.ico"
status = 200
