[build]
publish = "static"
command = """
curl -LsSf https://astral.sh/uv/install.sh | sh && \
bun run build && \
/opt/buildhome/.local/bin/uv sync && \
/opt/buildhome/.local/bin/uv run ssg.py
"""

[[redirects]]
from = "/api/*"
to = "/api/:splat.json"
status = 200

[[redirects]]
from = "/static/*"
to = "/:splat"
status = 200

[[redirects]]
from = "/favicon.ico"
to = "/icon/favicon.ico"
status = 200
